//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class mOperationType
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string cActive { get; set; }
    public string sRemark { get; set; }
    public string cDel { get; set; }
    public string sCode { get; set; }
    public string cManage { get; set; }
    public Nullable<int> nCreateID { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class mTCompany
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string cActive { get; set; }
    public string sRemark { get; set; }
    public string cDel { get; set; }
    public Nullable<int> CreateID { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> UpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string sCode { get; set; }
}

public partial class mTFacility
{
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<int> nHeaderID { get; set; }
    public Nullable<int> nLevel { get; set; }
    public string sRelation { get; set; }
    public int OperationTypeID { get; set; }
    public int CompanyID { get; set; }
    public string Description { get; set; }
    public string cActive { get; set; }
    public string sRemark { get; set; }
    public string cDel { get; set; }
    public Nullable<int> CreateID { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> UpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string sMappingCodePTT { get; set; }
    public string sSAPName { get; set; }
    public string sRefFacType { get; set; }
    public string sRefFacSubType { get; set; }
    public string sRefFacCode { get; set; }
    public string sInternalCode { get; set; }
}

public partial class mTFacility_Operationtype
{
    public int nFacID { get; set; }
    public int nOperationtypeID { get; set; }
}

public partial class mTIndicator
{
    public int ID { get; set; }
    public string Indicator { get; set; }
    public Nullable<int> nOrder { get; set; }
}

public partial class mTProductIndicator
{
    public int ProductID { get; set; }
    public Nullable<int> IDIndicator { get; set; }
    public Nullable<int> OperationTypeID { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
    public Nullable<int> sUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdateDate { get; set; }
    public string cDel { get; set; }
    public string sType { get; set; }
    public string cTotal { get; set; }
    public string cTotalAll { get; set; }
    public Nullable<int> nGroupCalc { get; set; }
    public Nullable<int> nOrder { get; set; }
    public string cHilight { get; set; }
    public string sUnit { get; set; }
    public string cManage { get; set; }
    public Nullable<int> nOption { get; set; }
    public Nullable<decimal> nDefaultFactor { get; set; }
    public string sSetHtml { get; set; }
}

public partial class mTProductIndicatorOutput
{
    public int ProductID { get; set; }
    public Nullable<int> IDIndicator { get; set; }
    public string ProductName { get; set; }
    public Nullable<decimal> nOrder { get; set; }
    public string sUnit { get; set; }
    public string cDel { get; set; }
    public Nullable<int> cUse { get; set; }
    public string sIsSpecific { get; set; }
    public string sType { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class mTProductIndicatorUnit
{
    public int ProductID { get; set; }
    public int UnitID { get; set; }
    public int cType { get; set; }
    public Nullable<int> IDIndicator { get; set; }
    public Nullable<decimal> nDefaultFactor { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class mTUnit
{
    public int UnitID { get; set; }
    public string UnitName { get; set; }
    public Nullable<decimal> nFactor { get; set; }
    public string sComment { get; set; }
    public string cDel { get; set; }
    public string cActive { get; set; }
    public Nullable<int> nCreateID { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cManage { get; set; }
}

public partial class mTUser
{
    public int ID { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string Firstname { get; set; }
    public string Lastname { get; set; }
    public string Company { get; set; }
    public string BusinessUnit { get; set; }
    public string Department { get; set; }
    public string Position { get; set; }
    public string Email { get; set; }
    public string Tel { get; set; }
    public Nullable<System.DateTime> Joined { get; set; }
    public Nullable<System.DateTime> LastVisit { get; set; }
    public string IP { get; set; }
    public string IsActivated { get; set; }
    public string IsExpired { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public Nullable<int> BusinessUnitID { get; set; }
    public Nullable<int> DepartmentID { get; set; }
    public Nullable<int> FacilityID { get; set; }
    public string cActive { get; set; }
    public string cDel { get; set; }
    public Nullable<int> nCreateID { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string PasswordEncrypt { get; set; }
    public string cNewRegister { get; set; }
    public Nullable<System.DateTime> dRegister { get; set; }
    public string sRemarkRegister { get; set; }
    public Nullable<System.DateTime> dLastResponseSV { get; set; }
    public string IsLockUser { get; set; }
    public string cUserType { get; set; }
    public string sUserCode { get; set; }
}

public partial class mTUser_FacilityPermission
{
    public int nUserID { get; set; }
    public int nRoleID { get; set; }
    public int nFacilityID { get; set; }
    public int nGroupIndicatorID { get; set; }
    public Nullable<int> nPermission { get; set; }
}

public partial class mTUserInRole
{
    public int nUID { get; set; }
    public int nRoleID { get; set; }
}

public partial class mTUserRole
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public string cDel { get; set; }
    public string cActive { get; set; }
    public Nullable<int> CreateID { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> UpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class mTWorkFlow
{
    public int IDFac { get; set; }
    public int IDIndicator { get; set; }
    public Nullable<int> L1 { get; set; }
    public Nullable<int> L2 { get; set; }
    public Nullable<int> L3 { get; set; }
    public Nullable<int> L4 { get; set; }
    public Nullable<int> nUpdateID { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cDel { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class T_Logmail
{
    public int nID { get; set; }
    public Nullable<System.DateTime> dSend { get; set; }
    public string sFrom { get; set; }
    public string sTo { get; set; }
    public string sCC { get; set; }
    public string sContent { get; set; }
    public Nullable<int> nDataID { get; set; }
    public Nullable<bool> bStatus { get; set; }
    public string sMessage { get; set; }
    public string sPagename { get; set; }
}

public partial class TAPI_User
{
    public int ID { get; set; }
    public string sUsername { get; set; }
    public string sPassword { get; set; }
    public string sType { get; set; }
}

public partial class TCheckCustomTarget
{
    public int FormID { get; set; }
    public string cIsCustomTarget { get; set; }
    public string cType { get; set; }
}

public partial class TComplaint
{
    public int FormID { get; set; }
    public int nComplaintID { get; set; }
    public Nullable<int> nComplaintTypeID { get; set; }
    public Nullable<System.DateTime> ComplaintDate { get; set; }
    public string sIssueBy { get; set; }
    public string sSubject { get; set; }
    public Nullable<int> nComplaintByID { get; set; }
    public string sComplaintByOther { get; set; }
    public string sDetail { get; set; }
    public string sCorrectiveAction { get; set; }
    public string sStatus { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
}

public partial class TComplaint_File
{
    public int FormID { get; set; }
    public int nComplaintID { get; set; }
    public int nFileID { get; set; }
    public string sPath { get; set; }
    public string sSysFileName { get; set; }
    public string sFileName { get; set; }
    public string sDescription { get; set; }
}

public partial class TComplaint_Impact
{
    public int FormID { get; set; }
    public int nComplaintID { get; set; }
    public int nImpactTypeID { get; set; }
    public string sOther { get; set; }
}

public partial class TComplaint_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TCompliance
{
    public int FormID { get; set; }
    public int nComplianceID { get; set; }
    public Nullable<System.DateTime> ComplianceDate { get; set; }
    public string sDocNumber { get; set; }
    public string sIssueBy { get; set; }
    public string sSubject { get; set; }
    public string sDetail { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
}

public partial class TCompliance_File
{
    public int FormID { get; set; }
    public int nComplianceID { get; set; }
    public int nFileID { get; set; }
    public string sPath { get; set; }
    public string sSysFileName { get; set; }
    public string sFileName { get; set; }
    public string sDescription { get; set; }
}

public partial class TCompliance_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TContactUs
{
    public int nContactID { get; set; }
    public string sContactName { get; set; }
    public string sContactEmail { get; set; }
    public string sContactTel { get; set; }
    public string sSubject { get; set; }
    public string sDetail { get; set; }
    public string sContactFile { get; set; }
    public string sContactPath { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public string sAnswer { get; set; }
    public Nullable<int> nAnswerBy { get; set; }
    public Nullable<System.DateTime> dAnswer { get; set; }
    public string sAnsFile { get; set; }
    public string sAnsPath { get; set; }
    public string cDel { get; set; }
    public string cStatusAns { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string sContactSysFile { get; set; }
    public string sAnsSysFile { get; set; }
}

public partial class TData_Type
{
    public int nID { get; set; }
    public Nullable<int> IndicatorID { get; set; }
    public string sName { get; set; }
    public string sType { get; set; }
    public string cActive { get; set; }
    public Nullable<int> nOrder { get; set; }
    public Nullable<int> nReferenceID { get; set; }
}

public partial class TEffluent_Option
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public string sOption { get; set; }
    public string sValuesPercent { get; set; }
    public Nullable<int> nNumberOfPoint { get; set; }
    public string sPercentOfPoint { get; set; }
}

public partial class TEffluent_OtherProduct_Point
{
    public int FormID { get; set; }
    public int nPointID { get; set; }
    public int nOtherID { get; set; }
    public Nullable<int> nProductID { get; set; }
    public Nullable<int> nUnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
}

public partial class TEffluent_Point
{
    public int FormID { get; set; }
    public int nPointID { get; set; }
    public string sPointName { get; set; }
    public string sOption1 { get; set; }
    public string sOption2 { get; set; }
    public string sPercent { get; set; }
    public Nullable<int> nDischargeTo { get; set; }
    public Nullable<int> nTreamentMethod { get; set; }
    public string sOtherTreamentMethod { get; set; }
    public Nullable<int> nArea { get; set; }
    public string sPointType { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
}

public partial class TEffluent_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TEffluent_Product_Point
{
    public int FormID { get; set; }
    public int nPointID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
}

public partial class TEffluent_Remark
{
    public int FormID { get; set; }
    public int nVersion { get; set; }
    public int ProductID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
}

public partial class TEffluentUseProduct
{
    public int ID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> OperationTypeID { get; set; }
    public Nullable<decimal> nOrder { get; set; }
    public string cSetCode { get; set; }
}

public partial class TEmission_OtherProduct_Stack
{
    public int FormID { get; set; }
    public int nStackID { get; set; }
    public int nOtherProductID { get; set; }
    public int ProductID { get; set; }
    public int nID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public Nullable<int> nOptionProduct { get; set; }
    public string cIsVOCs { get; set; }
}

public partial class TEmission_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TEmission_Product_ByType
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public string sType { get; set; }
    public int UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TEmission_Product_Stack
{
    public int FormID { get; set; }
    public int nStackID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public Nullable<int> nOptionProduct { get; set; }
}

public partial class TEmission_Remark
{
    public int FormID { get; set; }
    public int nVersion { get; set; }
    public int ProductID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
}

public partial class TEmission_Stack
{
    public int FormID { get; set; }
    public int nStackID { get; set; }
    public string sStackName { get; set; }
    public Nullable<int> nOrder { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
    public string sStackType { get; set; }
}

public partial class TEmission_VOC
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string sOption { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TEmissionUseProduct
{
    public int ID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> OperationTypeID { get; set; }
    public Nullable<decimal> nOrder { get; set; }
    public string cSetCode { get; set; }
}

public partial class TEPI_Forms
{
    public int FormID { get; set; }
    public string sYear { get; set; }
    public int IDIndicator { get; set; }
    public int OperationTypeID { get; set; }
    public Nullable<int> FacilityID { get; set; }
    public Nullable<int> ResponsiblePerson { get; set; }
    public Nullable<int> Quater { get; set; }
    public Nullable<System.DateTime> dSendate { get; set; }
    public string cStatus { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
    public Nullable<int> sUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdateDate { get; set; }
    public Nullable<int> nStatusIDQ1 { get; set; }
    public Nullable<int> nStatusIDQ2 { get; set; }
    public Nullable<int> nStatusIDQ3 { get; set; }
    public Nullable<int> nStatusIDQ4 { get; set; }
}

public partial class TEPI_Forms_Deviate
{
    public int FormID { get; set; }
    public int Month { get; set; }
    public int nProductID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> nActionBy { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
}

public partial class TEPI_Forms_File
{
    public int FormID { get; set; }
    public int nFileID { get; set; }
    public string sPath { get; set; }
    public string sSysFileName { get; set; }
    public string sFileName { get; set; }
    public string sDescription { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
}

public partial class TEPI_TransferPTT
{
    public int nYear { get; set; }
    public int nFacilityID { get; set; }
    public int nIndicatorID { get; set; }
    public int nQuarter { get; set; }
    public Nullable<int> nStatusID { get; set; }
    public Nullable<int> nActionBy { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
}

public partial class TEPI_TransferPTT_Log
{
    public long nLogID { get; set; }
    public Nullable<int> nYear { get; set; }
    public Nullable<int> nFacilityID { get; set; }
    public Nullable<int> nIndicatorID { get; set; }
    public Nullable<int> nQuarter { get; set; }
    public Nullable<int> nStatusID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> nActionBy { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
}

public partial class TEPI_TransferPTT_SubFacility
{
    public int nYear { get; set; }
    public int nHeaderID { get; set; }
    public int nFacilityID { get; set; }
    public int nIndicatorID { get; set; }
    public int nQuarterID { get; set; }
    public Nullable<int> nStatusID { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
}

public partial class TEPI_Workflow
{
    public int nReportID { get; set; }
    public int FormID { get; set; }
    public int nMonth { get; set; }
    public Nullable<int> nStatusID { get; set; }
    public Nullable<int> nActionBy { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
    public Nullable<int> nHistoryStatusID { get; set; }
}

public partial class TEPI_Workflow_History
{
    public long nLogID { get; set; }
    public int nReportID { get; set; }
    public Nullable<int> nFromStatusID { get; set; }
    public Nullable<int> nToStatusID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> nActionBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
}

public partial class TIntensity_Cylinder
{
    public int FormID { get; set; }
    public int CylinderID { get; set; }
    public string sCylinderType { get; set; }
    public string sFactor { get; set; }
    public string sTotal { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
}

public partial class TIntensity_Cylinder_Main
{
    public int FormID { get; set; }
    public string sCylinderOption { get; set; }
    public Nullable<int> nCylinderTypeID { get; set; }
    public string sTotal { get; set; }
}

public partial class TIntensity_DisplayInput
{
    public int ID { get; set; }
    public Nullable<int> OperationTypeID { get; set; }
    public Nullable<int> DisplayType { get; set; }
    public string sUrl { get; set; }
}

public partial class TIntensity_Other
{
    public int FormID { get; set; }
    public int UnderProductID { get; set; }
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public Nullable<decimal> Factor { get; set; }
    public int UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string sUnitSF { get; set; }
}

public partial class TIntensity_Remark
{
    public int FormID { get; set; }
    public int nVersion { get; set; }
    public int ProductID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
}

public partial class TIntensityDominator
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public Nullable<decimal> SpecificFactor { get; set; }
}

public partial class TIntensityUseProduct
{
    public int ID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> OperationTypeID { get; set; }
    public Nullable<decimal> nOrder { get; set; }
}

public partial class TLogbypass
{
    public int nLogID { get; set; }
    public int nYear { get; set; }
    public Nullable<int> nUserID { get; set; }
    public Nullable<int> nBypassToID { get; set; }
    public Nullable<System.DateTime> dBypass { get; set; }
}

public partial class TM_ComplaintType
{
    public int nID { get; set; }
    public string sName { get; set; }
    public Nullable<int> nType { get; set; }
    public string cActive { get; set; }
    public string cDel { get; set; }
    public Nullable<int> nCreateBy { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cManage { get; set; }
}

public partial class TM_Effluent_OtherProduct
{
    public int nProductID { get; set; }
    public string sName { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cActive { get; set; }
    public string cDel { get; set; }
}

public partial class TM_Effluent_Unit
{
    public int nUnitID { get; set; }
    public string sName { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cActive { get; set; }
    public string cDel { get; set; }
}

public partial class TM_Emission_OtherProduct
{
    public int nProductID { get; set; }
    public string sName { get; set; }
    public Nullable<int> nAddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cActive { get; set; }
    public string cDel { get; set; }
}

public partial class TM_WasteDisposal
{
    public int ID { get; set; }
    public string sCode { get; set; }
    public string sName { get; set; }
    public Nullable<int> nTypeID { get; set; }
    public Nullable<int> nCreateBy { get; set; }
    public Nullable<System.DateTime> dCreate { get; set; }
    public Nullable<int> nUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public string cActive { get; set; }
    public string cDel { get; set; }
}

public partial class TMaterial_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string sRemark { get; set; }
    public Nullable<double> nDefaultFactor { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
    public Nullable<int> sUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdateDate { get; set; }
    public Nullable<int> UnitID { get; set; }
    public Nullable<int> UnitID2 { get; set; }
    public string Target { get; set; }
    public Nullable<int> nOption { get; set; }
    public string sReporting { get; set; }
}

public partial class TMaterial_ProductData
{
    public int nSubProductID { get; set; }
    public int nUnderbyProductID { get; set; }
    public int FormID { get; set; }
    public string sName { get; set; }
    public Nullable<int> nOption { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string nTotal { get; set; }
    public string Target { get; set; }
    public string Density { get; set; }
    public Nullable<int> nUnitID { get; set; }
}

public partial class TMaterial_Remark
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public int nVersion { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
}

public partial class TMenu
{
    public int nMenuID { get; set; }
    public Nullable<int> sMenuOrder { get; set; }
    public string sMenuName { get; set; }
    public Nullable<int> sMenuHeadID { get; set; }
    public string nSecurity { get; set; }
    public string cSub { get; set; }
    public Nullable<int> nLevel { get; set; }
    public string sMenuLink { get; set; }
    public string sLinkNavigat { get; set; }
    public string cType { get; set; }
    public string cActive { get; set; }
    public Nullable<int> ngroup { get; set; }
    public string setPRMS { get; set; }
    public string sPicture { get; set; }
    public string flage_Menu { get; set; }
    public string sParameter { get; set; }
    public string sClassIcon { get; set; }
}

public partial class TMenu_Permission
{
    public int nUserID { get; set; }
    public int nRoleID { get; set; }
    public int nMenuID { get; set; }
    public Nullable<int> nPermission { get; set; }
}

public partial class TProduct_Tooltip
{
    public int ProductID { get; set; }
    public int IDIndicator { get; set; }
    public int cType { get; set; }
    public int TooltipID { get; set; }
}

public partial class TProductOutput
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string nTotal { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
}

public partial class TProductOutput_Intensity
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public string Target { get; set; }
}

public partial class TReport_Indicator
{
    public int ID { get; set; }
    public Nullable<int> ProductID { get; set; }
    public Nullable<int> UseIndicator { get; set; }
    public string UseReportType { get; set; }
    public string TargetIndicator { get; set; }
    public Nullable<int> RefProdcutID { get; set; }
    public string sProductType { get; set; }
}

public partial class TSpill
{
    public int FormID { get; set; }
    public int nSpillID { get; set; }
    public Nullable<int> PrimaryReasonID { get; set; }
    public string sOtherPrimary { get; set; }
    public string SpillType { get; set; }
    public Nullable<int> SpillOfID { get; set; }
    public string sOtherSpillOf { get; set; }
    public string Volume { get; set; }
    public Nullable<int> UnitVolumeID { get; set; }
    public Nullable<int> SpillToID { get; set; }
    public Nullable<int> SpillByID { get; set; }
    public Nullable<int> Signification1ID { get; set; }
    public Nullable<int> Signification2ID { get; set; }
    public Nullable<System.DateTime> SpillDate { get; set; }
    public string sDescription { get; set; }
    public string IncidentDescription { get; set; }
    public string RecoveryAction { get; set; }
    public Nullable<int> AddBy { get; set; }
    public Nullable<System.DateTime> dAdd { get; set; }
    public string sOtherSpillTo { get; set; }
    public string sIsSensitiveArea { get; set; }
    public string sIncidenceNo { get; set; }
    public string sSubstanceName { get; set; }
    public Nullable<int> LOPCTierID { get; set; }
    public string Density { get; set; }
    public string sOtherSpillBy { get; set; }
}

public partial class TSpill_File
{
    public int FormID { get; set; }
    public int nSpillID { get; set; }
    public int nFileID { get; set; }
    public string sPath { get; set; }
    public string sSysFileName { get; set; }
    public string sFileName { get; set; }
    public string sDescription { get; set; }
}

public partial class TSpill_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string IsCheckM1 { get; set; }
    public string IsCheckM2 { get; set; }
    public string IsCheckM3 { get; set; }
    public string IsCheckM4 { get; set; }
    public string IsCheckM5 { get; set; }
    public string IsCheckM6 { get; set; }
    public string IsCheckM7 { get; set; }
    public string IsCheckM8 { get; set; }
    public string IsCheckM9 { get; set; }
    public string IsCheckM10 { get; set; }
    public string IsCheckM11 { get; set; }
    public string IsCheckM12 { get; set; }
}

public partial class TStatus_Workflow
{
    public int nStatustID { get; set; }
    public string sStatusName { get; set; }
    public string sShorttStatus { get; set; }
    public string cType { get; set; }
    public string cActive { get; set; }
    public Nullable<int> nLevelUse { get; set; }
    public string cTypeUse { get; set; }
    public string sColor { get; set; }
    public string sImage { get; set; }
}

public partial class TTooltip_Product
{
    public int ID { get; set; }
    public string Name { get; set; }
}

public partial class TUseProductOutput
{
    public int ProductID { get; set; }
    public int IDIndicator { get; set; }
    public int OperationtypeID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public Nullable<decimal> Factor { get; set; }
    public Nullable<decimal> nOrder { get; set; }
}

public partial class TValidate_Data
{
    public int nFacilitID { get; set; }
    public int nIndID { get; set; }
    public Nullable<decimal> nPercent { get; set; }
    public string cActive { get; set; }
    public Nullable<System.DateTime> dUpdate { get; set; }
    public Nullable<int> Updateby { get; set; }
}

public partial class TViewMenu_History
{
    public long nLogID { get; set; }
    public Nullable<int> nUserID { get; set; }
    public Nullable<System.DateTime> dAction { get; set; }
    public Nullable<int> nMenuID { get; set; }
}

public partial class TWaste_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
    public string sRemark { get; set; }
    public Nullable<decimal> nDefaultFactor { get; set; }
    public string PreviousYear { get; set; }
    public string ReportingYear { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
    public Nullable<int> sUpdateBy { get; set; }
    public Nullable<System.DateTime> dUpdateDate { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string Target { get; set; }
}

public partial class TWaste_Product_data
{
    public int nSubProductID { get; set; }
    public int FormID { get; set; }
    public int UnderProductID { get; set; }
    public string ProductName { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public Nullable<int> nDisposalID { get; set; }
}

public partial class TWaste_Remark
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public int nVersion { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
}

public partial class TWater_Product
{
    public int FormID { get; set; }
    public int ProductID { get; set; }
    public Nullable<int> UnitID { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string Target { get; set; }
    public string Q1 { get; set; }
    public string Q2 { get; set; }
    public string Q3 { get; set; }
    public string Q4 { get; set; }
    public string H1 { get; set; }
    public string H2 { get; set; }
    public string nTotal { get; set; }
}

public partial class TWater_ProductData
{
    public int nSubProductID { get; set; }
    public int nUnderbyProductID { get; set; }
    public int FormID { get; set; }
    public string sName { get; set; }
    public Nullable<int> nOption { get; set; }
    public string M1 { get; set; }
    public string M2 { get; set; }
    public string M3 { get; set; }
    public string M4 { get; set; }
    public string M5 { get; set; }
    public string M6 { get; set; }
    public string M7 { get; set; }
    public string M8 { get; set; }
    public string M9 { get; set; }
    public string M10 { get; set; }
    public string M11 { get; set; }
    public string M12 { get; set; }
    public string nTotal { get; set; }
    public string Target { get; set; }
    public Nullable<int> nUnitID { get; set; }
}

public partial class TWater_Remark
{
    public int FormID { get; set; }
    public int nVersion { get; set; }
    public int ProductID { get; set; }
    public string sRemark { get; set; }
    public Nullable<int> sAddBy { get; set; }
    public Nullable<System.DateTime> dAddDate { get; set; }
}

public partial class v_TM_SAP_ALLFAC
{
    public string sCode { get; set; }
    public string sShortName { get; set; }
    public string sName { get; set; }
    public string sType { get; set; }
    public string sCompCode { get; set; }
}

public partial class v_TM_SAP_Company
{
    public string sCompCode { get; set; }
    public string sCompAbbr { get; set; }
    public string sCompName { get; set; }
    public string sBusinessUnit { get; set; }
    public string sBusinessSegmen { get; set; }
    public string sHoldingStatus { get; set; }
}
