//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PTTGC_EPIEntities : DbContext
{
    public PTTGC_EPIEntities()
        : base("name=PTTGC_EPIEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<TM_WasteDisposal> TM_WasteDisposal { get; set; }
    public virtual DbSet<TWater_ProductData> TWater_ProductData { get; set; }
    public virtual DbSet<mOperationType> mOperationType { get; set; }
    public virtual DbSet<mTCompany> mTCompany { get; set; }
    public virtual DbSet<mTFacility> mTFacility { get; set; }
    public virtual DbSet<mTFacility_Operationtype> mTFacility_Operationtype { get; set; }
    public virtual DbSet<mTIndicator> mTIndicator { get; set; }
    public virtual DbSet<mTProductIndicator> mTProductIndicator { get; set; }
    public virtual DbSet<mTProductIndicatorOutput> mTProductIndicatorOutput { get; set; }
    public virtual DbSet<mTProductIndicatorUnit> mTProductIndicatorUnit { get; set; }
    public virtual DbSet<mTUnit> mTUnit { get; set; }
    public virtual DbSet<mTUser> mTUser { get; set; }
    public virtual DbSet<mTUser_FacilityPermission> mTUser_FacilityPermission { get; set; }
    public virtual DbSet<mTUserInRole> mTUserInRole { get; set; }
    public virtual DbSet<mTUserRole> mTUserRole { get; set; }
    public virtual DbSet<mTWorkFlow> mTWorkFlow { get; set; }
    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    public virtual DbSet<T_Logmail> T_Logmail { get; set; }
    public virtual DbSet<TCheckCustomTarget> TCheckCustomTarget { get; set; }
    public virtual DbSet<TComplaint> TComplaint { get; set; }
    public virtual DbSet<TComplaint_File> TComplaint_File { get; set; }
    public virtual DbSet<TComplaint_Impact> TComplaint_Impact { get; set; }
    public virtual DbSet<TComplaint_Product> TComplaint_Product { get; set; }
    public virtual DbSet<TCompliance> TCompliance { get; set; }
    public virtual DbSet<TCompliance_File> TCompliance_File { get; set; }
    public virtual DbSet<TCompliance_Product> TCompliance_Product { get; set; }
    public virtual DbSet<TContactUs> TContactUs { get; set; }
    public virtual DbSet<TData_Type> TData_Type { get; set; }
    public virtual DbSet<TEffluent_Option> TEffluent_Option { get; set; }
    public virtual DbSet<TEffluent_OtherProduct_Point> TEffluent_OtherProduct_Point { get; set; }
    public virtual DbSet<TEffluent_Point> TEffluent_Point { get; set; }
    public virtual DbSet<TEffluent_Product> TEffluent_Product { get; set; }
    public virtual DbSet<TEffluent_Product_Point> TEffluent_Product_Point { get; set; }
    public virtual DbSet<TEffluent_Remark> TEffluent_Remark { get; set; }
    public virtual DbSet<TEffluentUseProduct> TEffluentUseProduct { get; set; }
    public virtual DbSet<TEmission_OtherProduct_Stack> TEmission_OtherProduct_Stack { get; set; }
    public virtual DbSet<TEmission_Product> TEmission_Product { get; set; }
    public virtual DbSet<TEmission_Product_ByType> TEmission_Product_ByType { get; set; }
    public virtual DbSet<TEmission_Product_Stack> TEmission_Product_Stack { get; set; }
    public virtual DbSet<TEmission_Remark> TEmission_Remark { get; set; }
    public virtual DbSet<TEmission_Stack> TEmission_Stack { get; set; }
    public virtual DbSet<TEmission_VOC> TEmission_VOC { get; set; }
    public virtual DbSet<TEmissionUseProduct> TEmissionUseProduct { get; set; }
    public virtual DbSet<TEPI_Forms> TEPI_Forms { get; set; }
    public virtual DbSet<TEPI_Forms_Deviate> TEPI_Forms_Deviate { get; set; }
    public virtual DbSet<TEPI_Forms_File> TEPI_Forms_File { get; set; }
    public virtual DbSet<TEPI_Workflow> TEPI_Workflow { get; set; }
    public virtual DbSet<TEPI_Workflow_History> TEPI_Workflow_History { get; set; }
    public virtual DbSet<TIntensity_Cylinder> TIntensity_Cylinder { get; set; }
    public virtual DbSet<TIntensity_Cylinder_Main> TIntensity_Cylinder_Main { get; set; }
    public virtual DbSet<TIntensity_DisplayInput> TIntensity_DisplayInput { get; set; }
    public virtual DbSet<TIntensity_Other> TIntensity_Other { get; set; }
    public virtual DbSet<TIntensity_Remark> TIntensity_Remark { get; set; }
    public virtual DbSet<TIntensityDominator> TIntensityDominator { get; set; }
    public virtual DbSet<TIntensityUseProduct> TIntensityUseProduct { get; set; }
    public virtual DbSet<TLogbypass> TLogbypass { get; set; }
    public virtual DbSet<TM_ComplaintType> TM_ComplaintType { get; set; }
    public virtual DbSet<TM_Effluent_OtherProduct> TM_Effluent_OtherProduct { get; set; }
    public virtual DbSet<TM_Effluent_Unit> TM_Effluent_Unit { get; set; }
    public virtual DbSet<TM_Emission_OtherProduct> TM_Emission_OtherProduct { get; set; }
    public virtual DbSet<TMaterial_Product> TMaterial_Product { get; set; }
    public virtual DbSet<TMaterial_ProductData> TMaterial_ProductData { get; set; }
    public virtual DbSet<TMaterial_Remark> TMaterial_Remark { get; set; }
    public virtual DbSet<TMenu> TMenu { get; set; }
    public virtual DbSet<TMenu_Permission> TMenu_Permission { get; set; }
    public virtual DbSet<TProduct_Tooltip> TProduct_Tooltip { get; set; }
    public virtual DbSet<TProductOutput> TProductOutput { get; set; }
    public virtual DbSet<TProductOutput_Intensity> TProductOutput_Intensity { get; set; }
    public virtual DbSet<TReport_Indicator> TReport_Indicator { get; set; }
    public virtual DbSet<TSpill> TSpill { get; set; }
    public virtual DbSet<TSpill_File> TSpill_File { get; set; }
    public virtual DbSet<TSpill_Product> TSpill_Product { get; set; }
    public virtual DbSet<TStatus_Workflow> TStatus_Workflow { get; set; }
    public virtual DbSet<TTooltip_Product> TTooltip_Product { get; set; }
    public virtual DbSet<TUseProductOutput> TUseProductOutput { get; set; }
    public virtual DbSet<TValidate_Data> TValidate_Data { get; set; }
    public virtual DbSet<TWaste_Product> TWaste_Product { get; set; }
    public virtual DbSet<TWaste_Product_data> TWaste_Product_data { get; set; }
    public virtual DbSet<TWaste_Remark> TWaste_Remark { get; set; }
    public virtual DbSet<TWater_Product> TWater_Product { get; set; }
    public virtual DbSet<TWater_Remark> TWater_Remark { get; set; }
    public virtual DbSet<v_TM_SAP_Company> v_TM_SAP_Company { get; set; }
    public virtual DbSet<v_TM_SAP_ALLFAC> v_TM_SAP_ALLFAC { get; set; }
    public virtual DbSet<TEPI_TransferPTT> TEPI_TransferPTT { get; set; }
    public virtual DbSet<TEPI_TransferPTT_SubFacility> TEPI_TransferPTT_SubFacility { get; set; }
    public virtual DbSet<TEPI_TransferPTT_Log> TEPI_TransferPTT_Log { get; set; }
    public virtual DbSet<TAPI_User> TAPI_User { get; set; }
    public virtual DbSet<TViewMenu_History> TViewMenu_History { get; set; }
}
